/srv/wanna-build/logs/merge.*.log /srv/wanna-build/logs/signal.log {
       weekly
       rotate 30
       maxsize 50M
       copytruncate
       delaycompress
       compress
       compresscmd /usr/bin/zstd
       compressext .zst
       compressoptions -T0 -9
       uncompresscmd /usr/bin/unzstd
       dateext
       notifempty
       missingok
       create 660 wbadm wbadm
}

