
CREATE ROLE wbadm;
ALTER ROLE wbadm WITH NOSUPERUSER INHERIT CREATEROLE CREATEDB LOGIN;

CREATE ROLE "wb-buildd";
ALTER ROLE "wb-buildd" WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN;

CREATE ROLE wb_all;
ALTER ROLE wb_all WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB NOLOGIN;

CREATE ROLE wb_security;
ALTER ROLE wb_security WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB NOLOGIN;

GRANT wb_all, wb_security TO wbadm with ADMIN OPTION;

GRANT wb_all TO "wb-buildd" GRANTED BY wbadm;
GRANT wb_all TO wbadm GRANTED BY wbadm;

